config/routes.rb
Rails.application.routes.draw do

  resources :trips do
    resources :activities, shallow: true
    resources :expenses, :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :polls
  end

  devise_for :users 

  post 'trips/:trip_id/polls/:id/upvote' => "polls#upvote", :controller => :poll
  post 'trips/:trip_id/polls/:id/downvote' => "polls#downvote", :controller => :poll

  root "welcome#index"

  get 'mobile_users/new' => 'mobile_users#new'
  post 'mobile_users/new' => 'mobile_users#create'
  get 'mobile_trips/new' => 'mobile_trips#new'
  post 'mobile_trips/new' => 'mobile_trips#create'
  get 'mobile_trips/user_trips'
  post 'mobile_trips/user_trips' => 'mobile_trips#user_trips'
  get 'mobile_trips/trip_detail'
  post 'mobile_trips/trip_detail' => 'mobile_trips#trip_detail'
  get 'mobile_trips/activities_detail'
  post 'mobile_trips/activities_detail' => 'mobile_trips#activities_detail'
  get 'mobile_activities/new' => 'mobile_activities#new'
  post 'mobile_activities/new' => 'mobile_activities#create'

  get 'mobile_sessions/sign_in'
  post 'mobile_sessions/sign_in' => 'mobile_sessions#create_session'

  post 'trips/:id/invite' => "trips#invite"
  put 'trip_participations/:id' => "trip_participations#update"
  delete 'trip_participations/:id' => "trip_participations#destroy"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  include DateTimeHelper

	#for geocoder, sets latitude and longitude
	geocoded_by :location
	after_validation :geocode

  has_many :activity_participations, dependent: :destroy
  has_many :trip_participations, through: :activity_participations
  has_many :participants, through: :trip_participations, source: :traveler
  belongs_to :creator, class_name: "User"
  belongs_to :trip

  def start_time_display
    to_date_and_time(self.start_time)
  end

  def end_time_display
    to_date_and_time(self.end_time)
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @trip = Trip.find_by_id(params[:trip_id])
    @activities = Activity.where(trip_id: @trip.id)
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])
    @trip = @activity.trip
  end

  # GET /activities/new
  def new
    @trip = Trip.find(params[:trip_id])
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit

  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    @trip = Trip.find(params[:trip_id])
    @trip.activities << @activity
    current_user.created_activities << @activity

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
        # UserMailer.test_email(current_user).deliver
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
      # if request.env["HTTP_X_REQUESTED_WITH"] == "text/xml"
      # then request is from mobile app
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to trip_activities_path(@activity.trip.id), notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :description, :location, :start_time, :end_time, :trip_id, :creator_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activity_list.html.erb
<div class="pure-table">
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Location</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.name %></td>
        <td><%= activity.description %></td>
        <td><%= activity.location %></td>
        <td><%= activity.start_time_display %></td>
        <td><%= activity.end_time_display %></td>
        <td><%= link_to 'Show', activity_path(activity) %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Delete', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/activities/_form.html.erb
<%= form_for [@trip, @activity] do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location, placeholder: "e.g. Merchandise Mart, Chicago, IL" %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
 <!--  <div class="field">
    <%#= f.label :trip_id %><br>
    <%#= f.number_field :trip_id %>
  </div>
  <div class="field">
    <%#= f.label :creator_id %><br>
    <%#= f.number_field :creator_id %>
  </div> -->
  <div class="actions">
    <%= f.submit "Submit",  class="pure-button"%>
  </div>
<% end %>

app/views/activities/edit.html.erb
<div class="form_container">
	<div class="pure-form">
		<h1>Editing activity</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @activity %> |
		<%= link_to 'Back', trip_activities_path(@activity.trip.id) %>
	</div>
</div>

app/views/activities/edit.js.erb
$("#trip_show_binder").html("<%= escape_javascript(render 'form') %>");

app/views/activities/index.html.erb
<div class="container">
  <div class="pure-table">
		<div class="activity_list">

		<%= render 'activity_list' %>

		</div>
	</div>
</div>

app/views/activities/new.html.erb
<div class="form_container">
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', trip_activities_path(params[:trip_id]) %>
</div>

app/views/activities/new.js.erb
$("#trip_show_binder").html("<%= escape_javascript(render 'form') %>");

app/views/activities/show.html.erb
<div class="container">
  <div class="pure-table">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Name:</strong>
      <%= @activity.name %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @activity.description %>
    </p>

    <p>
      <strong>Location:</strong>
      <%= @activity.location %>
    </p>

    <p>
      <strong>Start time:</strong>
      <%= @activity.start_time %>
    </p>

    <p>
      <strong>End time:</strong>
      <%= @activity.end_time %>
    </p>

    <p>
      <strong>Trip:</strong>
      <%= @activity.trip_id %>
    </p>

    <p>
      <strong>Creator:</strong>
      <%= @activity.creator_id %>
    </p>

    <%= link_to 'My Trips', trips_path %> |
    <%= link_to 'Back to Trip', trip_path(@trip.id) %> |
    <%= link_to 'Edit', edit_activity_path(@activity) %> |
    <%= link_to 'Delete', @activity, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>